apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    url: http://gateway:3100
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
